# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredImageDoc(TypedDict):
    pass

class OptionalImageDoc(TypedDict, total=False):
    # The ID of the BaseDoc. This is useful for indexing in vector stores. If not set by user, it will automatically be assigned a random value
    id: str

    # URL of an image file
    url: str

    # Bytes representation of the Image.
    bytes: typing.IO

class ImageDoc(RequiredImageDoc, OptionalImageDoc):
    pass
