# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

import unittest

import jina_ai_python_sdk
from jina_ai_python_sdk.model.bulk_embedding_job_status import BulkEmbeddingJobStatus
from jina_ai_python_sdk import configuration


class TestBulkEmbeddingJobStatus(unittest.TestCase):
    """BulkEmbeddingJobStatus unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
