# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

import unittest

import jina_ai_python_sdk
from jina_ai_python_sdk.model.api_schemas_rank_text_doc import ApiSchemasRankTextDoc
from jina_ai_python_sdk import configuration


class TestApiSchemasRankTextDoc(unittest.TestCase):
    """ApiSchemasRankTextDoc unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
