# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from jina_ai_python_sdk.paths.v1_bulk_embeddings_job_id_download_result.post import DownloadResultPost
from jina_ai_python_sdk.paths.v1_bulk_embeddings_job_id.get import GetJob
from jina_ai_python_sdk.paths.v1_bulk_embeddings.post import UploadFileAndGetEmbeddings
from jina_ai_python_sdk.apis.tags.bulk_embeddings_api_raw import BulkEmbeddingsApiRaw


class BulkEmbeddingsApi(
    DownloadResultPost,
    GetJob,
    UploadFileAndGetEmbeddings,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BulkEmbeddingsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BulkEmbeddingsApiRaw(api_client)
