# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from jina_ai_python_sdk.paths.v1_bulk_embeddings_job_id_download_result.post import DownloadResultPostRaw
from jina_ai_python_sdk.paths.v1_bulk_embeddings_job_id.get import GetJobRaw
from jina_ai_python_sdk.paths.v1_bulk_embeddings.post import UploadFileAndGetEmbeddingsRaw


class BulkEmbeddingsApiRaw(
    DownloadResultPostRaw,
    GetJobRaw,
    UploadFileAndGetEmbeddingsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
