# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from jina_ai_python_sdk.paths.v1_embeddings.post import CreateRepresentation
from jina_ai_python_sdk.apis.tags.embeddings_api_raw import EmbeddingsApiRaw


class EmbeddingsApi(
    CreateRepresentation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmbeddingsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmbeddingsApiRaw(api_client)
