# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from jina_ai_python_sdk.paths.root.get import CheckStatus
from jina_ai_python_sdk.apis.tags.health_api_raw import HealthApiRaw


class HealthApi(
    CheckStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HealthApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HealthApiRaw(api_client)
