# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from jina_ai_python_sdk.paths.v1_multi_embeddings.post import GenerateEmbeddingsRaw


class MultiEmbeddingsApiRaw(
    GenerateEmbeddingsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
