# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from jina_ai_python_sdk.paths.v1_rerank.post import PairRanking
from jina_ai_python_sdk.apis.tags.rerank_api_raw import RerankApiRaw


class RerankApi(
    PairRanking,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RerankApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RerankApiRaw(api_client)
