# coding: utf-8

# flake8: noqa

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

__version__ = "0.0.86"

# import ApiClient
from jina_ai_python_sdk.api_client import ApiClient

# import Configuration
from jina_ai_python_sdk.configuration import Configuration

# import exceptions
from jina_ai_python_sdk.exceptions import OpenApiException
from jina_ai_python_sdk.exceptions import ApiAttributeError
from jina_ai_python_sdk.exceptions import ApiTypeError
from jina_ai_python_sdk.exceptions import ApiValueError
from jina_ai_python_sdk.exceptions import ApiKeyError
from jina_ai_python_sdk.exceptions import ApiException

from jina_ai_python_sdk.client import JinaAi
