# coding: utf-8
"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from jina_ai_python_sdk.client_custom import ClientCustom
from jina_ai_python_sdk.configuration import Configuration
from jina_ai_python_sdk.api_client import ApiClient
from jina_ai_python_sdk.type_util import copy_signature
from jina_ai_python_sdk.apis.tags.bulk_embeddings_api import BulkEmbeddingsApi
from jina_ai_python_sdk.apis.tags.embeddings_api import EmbeddingsApi
from jina_ai_python_sdk.apis.tags.health_api import HealthApi
from jina_ai_python_sdk.apis.tags.multi_embeddings_api import MultiEmbeddingsApi
from jina_ai_python_sdk.apis.tags.rerank_api import RerankApi



class JinaAi(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.bulk_embeddings: BulkEmbeddingsApi = BulkEmbeddingsApi(api_client)
        self.embeddings: EmbeddingsApi = EmbeddingsApi(api_client)
        self.health: HealthApi = HealthApi(api_client)
        self.multi_embeddings: MultiEmbeddingsApi = MultiEmbeddingsApi(api_client)
        self.rerank: RerankApi = RerankApi(api_client)
