# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import jina_ai_python_sdk
from jina_ai_python_sdk.paths.v1_rerank import post
from jina_ai_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1Rerank(ApiTestMixin, unittest.TestCase):
    """
    V1Rerank unit test stubs
        Rank
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
