# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from jina_ai_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from jina_ai_python_sdk.api_response import AsyncGeneratorResponse
from jina_ai_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from jina_ai_python_sdk import schemas  # noqa: F401

from jina_ai_python_sdk.model.http_validation_error import HTTPValidationError as HTTPValidationErrorSchema
from jina_ai_python_sdk.model.body_start_bulk_embedding_v1_bulk_embeddings_post import BodyStartBulkEmbeddingV1BulkEmbeddingsPost as BodyStartBulkEmbeddingV1BulkEmbeddingsPostSchema
from jina_ai_python_sdk.model.bulk_embedding_job_response import BulkEmbeddingJobResponse as BulkEmbeddingJobResponseSchema

from jina_ai_python_sdk.type.body_start_bulk_embedding_v1_bulk_embeddings_post import BodyStartBulkEmbeddingV1BulkEmbeddingsPost
from jina_ai_python_sdk.type.bulk_embedding_job_response import BulkEmbeddingJobResponse
from jina_ai_python_sdk.type.http_validation_error import HTTPValidationError

from ...api_client import Dictionary
from jina_ai_python_sdk.pydantic.bulk_embedding_job_response import BulkEmbeddingJobResponse as BulkEmbeddingJobResponsePydantic
from jina_ai_python_sdk.pydantic.body_start_bulk_embedding_v1_bulk_embeddings_post import BodyStartBulkEmbeddingV1BulkEmbeddingsPost as BodyStartBulkEmbeddingV1BulkEmbeddingsPostPydantic
from jina_ai_python_sdk.pydantic.http_validation_error import HTTPValidationError as HTTPValidationErrorPydantic

# body param
SchemaForRequestBodyMultipartFormData = BodyStartBulkEmbeddingV1BulkEmbeddingsPostSchema


request_body_body_start_bulk_embedding_v1_bulk_embeddings_post = api_client.RequestBody(
    content={
        'multipart/form-data': api_client.MediaType(
            schema=SchemaForRequestBodyMultipartFormData),
    },
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = BulkEmbeddingJobResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: BulkEmbeddingJobResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: BulkEmbeddingJobResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor422ResponseBodyApplicationJson = HTTPValidationErrorSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: HTTPValidationError


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: HTTPValidationError


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _upload_file_and_get_embeddings_mapped_args(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if file is not None:
            _body["file"] = file
        if email is not None:
            _body["email"] = email
        if model is not None:
            _body["model"] = model
        args.body = _body
        return args

    async def _aupload_file_and_get_embeddings_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'multipart/form-data',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Start Bulk Embedding
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/bulk-embeddings',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_body_start_bulk_embedding_v1_bulk_embeddings_post.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _upload_file_and_get_embeddings_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'multipart/form-data',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Start Bulk Embedding
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/bulk-embeddings',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_body_start_bulk_embedding_v1_bulk_embeddings_post.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UploadFileAndGetEmbeddingsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupload_file_and_get_embeddings(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._upload_file_and_get_embeddings_mapped_args(
            file=file,
            model=model,
            email=email,
        )
        return await self._aupload_file_and_get_embeddings_oapg(
            body=args.body,
            **kwargs,
        )
    
    def upload_file_and_get_embeddings(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._upload_file_and_get_embeddings_mapped_args(
            file=file,
            model=model,
            email=email,
        )
        return self._upload_file_and_get_embeddings_oapg(
            body=args.body,
        )

class UploadFileAndGetEmbeddings(BaseApi):

    async def aupload_file_and_get_embeddings(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> BulkEmbeddingJobResponsePydantic:
        raw_response = await self.raw.aupload_file_and_get_embeddings(
            file=file,
            model=model,
            email=email,
            **kwargs,
        )
        if validate:
            return BulkEmbeddingJobResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(BulkEmbeddingJobResponsePydantic, raw_response.body)
    
    
    def upload_file_and_get_embeddings(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
        validate: bool = False,
    ) -> BulkEmbeddingJobResponsePydantic:
        raw_response = self.raw.upload_file_and_get_embeddings(
            file=file,
            model=model,
            email=email,
        )
        if validate:
            return BulkEmbeddingJobResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(BulkEmbeddingJobResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._upload_file_and_get_embeddings_mapped_args(
            file=file,
            model=model,
            email=email,
        )
        return await self._aupload_file_and_get_embeddings_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        file: typing.IO,
        model: str,
        email: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._upload_file_and_get_embeddings_mapped_args(
            file=file,
            model=model,
            email=email,
        )
        return self._upload_file_and_get_embeddings_oapg(
            body=args.body,
        )

