# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from jina_ai_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from jina_ai_python_sdk.api_response import AsyncGeneratorResponse
from jina_ai_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from jina_ai_python_sdk import schemas  # noqa: F401

from jina_ai_python_sdk.model.http_validation_error import HTTPValidationError as HTTPValidationErrorSchema
from jina_ai_python_sdk.model.api_schemas_rank_text_doc import ApiSchemasRankTextDoc as ApiSchemasRankTextDocSchema
from jina_ai_python_sdk.model.text_rank_input import TextRankInput as TextRankInputSchema
from jina_ai_python_sdk.model.ranking_output import RankingOutput as RankingOutputSchema

from jina_ai_python_sdk.type.text_rank_input import TextRankInput
from jina_ai_python_sdk.type.ranking_output import RankingOutput
from jina_ai_python_sdk.type.http_validation_error import HTTPValidationError
from jina_ai_python_sdk.type.api_schemas_rank_text_doc import ApiSchemasRankTextDoc

from ...api_client import Dictionary
from jina_ai_python_sdk.pydantic.text_rank_input import TextRankInput as TextRankInputPydantic
from jina_ai_python_sdk.pydantic.ranking_output import RankingOutput as RankingOutputPydantic
from jina_ai_python_sdk.pydantic.api_schemas_rank_text_doc import ApiSchemasRankTextDoc as ApiSchemasRankTextDocPydantic
from jina_ai_python_sdk.pydantic.http_validation_error import HTTPValidationError as HTTPValidationErrorPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = TextRankInputSchema


request_body_text_rank_input = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'HTTPBearer',
]
SchemaFor200ResponseBodyApplicationJson = RankingOutputSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: RankingOutput


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: RankingOutput


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor422ResponseBodyApplicationJson = HTTPValidationErrorSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: HTTPValidationError


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: HTTPValidationError


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '422': _response_for_422,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _pair_ranking_mapped_args(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if model is not None:
            _body["model"] = model
        if query is not None:
            _body["query"] = query
        if documents is not None:
            _body["documents"] = documents
        if top_n is not None:
            _body["top_n"] = top_n
        if return_documents is not None:
            _body["return_documents"] = return_documents
        args.body = _body
        return args

    async def _apair_ranking_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Rank
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/rerank',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_text_rank_input.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _pair_ranking_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Rank
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/rerank',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_text_rank_input.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class PairRankingRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def apair_ranking(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._pair_ranking_mapped_args(
            model=model,
            query=query,
            documents=documents,
            top_n=top_n,
            return_documents=return_documents,
        )
        return await self._apair_ranking_oapg(
            body=args.body,
            **kwargs,
        )
    
    def pair_ranking(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._pair_ranking_mapped_args(
            model=model,
            query=query,
            documents=documents,
            top_n=top_n,
            return_documents=return_documents,
        )
        return self._pair_ranking_oapg(
            body=args.body,
        )

class PairRanking(BaseApi):

    async def apair_ranking(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
        validate: bool = False,
        **kwargs,
    ) -> RankingOutputPydantic:
        raw_response = await self.raw.apair_ranking(
            model=model,
            query=query,
            documents=documents,
            top_n=top_n,
            return_documents=return_documents,
            **kwargs,
        )
        if validate:
            return RankingOutputPydantic(**raw_response.body)
        return api_client.construct_model_instance(RankingOutputPydantic, raw_response.body)
    
    
    def pair_ranking(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
        validate: bool = False,
    ) -> RankingOutputPydantic:
        raw_response = self.raw.pair_ranking(
            model=model,
            query=query,
            documents=documents,
            top_n=top_n,
            return_documents=return_documents,
        )
        if validate:
            return RankingOutputPydantic(**raw_response.body)
        return api_client.construct_model_instance(RankingOutputPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._pair_ranking_mapped_args(
            model=model,
            query=query,
            documents=documents,
            top_n=top_n,
            return_documents=return_documents,
        )
        return await self._apair_ranking_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        model: str,
        query: typing.Union[str, ApiSchemasRankTextDoc],
        documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]],
        top_n: typing.Optional[int] = None,
        return_documents: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._pair_ranking_mapped_args(
            model=model,
            query=query,
            documents=documents,
            top_n=top_n,
            return_documents=return_documents,
        )
        return self._pair_ranking_oapg(
            body=args.body,
        )

