# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from jina_ai_python_sdk.pydantic.api_schemas_embedding_text_embedding_input import ApiSchemasEmbeddingTextEmbeddingInput
from jina_ai_python_sdk.pydantic.image_embedding_input import ImageEmbeddingInput

EmbeddingsCreateRepresentationRequest = typing.Union[ApiSchemasEmbeddingTextEmbeddingInput,ImageEmbeddingInput]
