# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ImageDoc(BaseModel):
    # The ID of the BaseDoc. This is useful for indexing in vector stores. If not set by user, it will automatically be assigned a random value
    id: typing.Optional[str] = Field(None, alias='id')

    # URL of an image file
    url: typing.Optional[str] = Field(None, alias='url')

    # Bytes representation of the Image.
    bytes: typing.Optional[typing.IO] = Field(None, alias='bytes')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
