# coding: utf-8

"""
    The Jina Embedding Serving API

    This is the UniversalAPI to access all the Jina embedding models

    The version of the OpenAPI document: 0.0.86
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from jina_ai_python_sdk.pydantic.api_schemas_rank_text_doc import ApiSchemasRankTextDoc

class TextRankInput(BaseModel):
    # The identifier of the model.  Available models and corresponding param size and dimension: - `jina-embedding-t-en-v1`, 14m, 312 - `jina-embedding-s-en-v1`, 35m, 512 (default) - `jina-embedding-b-en-v1`, 110m, 768 - `jina-embedding-l-en-v1`, 330, 1024  For more information, please checkout our [technical blog](https://arxiv.org/abs/2307.11224). 
    model: str = Field(alias='model')

    # The search query
    query: typing.Union[str, ApiSchemasRankTextDoc] = Field(alias='query')

    # A list of text documents or strings to rerank. If a document is provided the text fields is required and all other fields will be preserved in the response.
    documents: typing.Union[typing.List[str], typing.List[ApiSchemasRankTextDoc]] = Field(alias='documents')

    # The number of most relevant documents or indices to return, defaults to the length of `documents`
    top_n: typing.Optional[int] = Field(None, alias='top_n')

    # If false, returns results without the doc text - the api will return a list of {index, relevance score} where index is inferred from the list passed into the request. If true, returns results with the doc text passed in - the api will return an ordered list of {index, text, relevance score} where index + text refers to the list passed into the request. Defaults to true
    return_documents: typing.Optional[bool] = Field(None, alias='return_documents')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
